# Generated by Django 4.0.5 on 2022-06-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Intersex', 'Uknown')], default='Male', max_length=30)),
                ('id_no', models.CharField(max_length=8, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('ward', models.CharField(max_length=50)),
                ('constituences', models.CharField(choices=[('Igembe Central', 'Igembe Central'), ('Igembe North', 'Igembe North'), ('Igembe South', 'Igembe South')], default='Igembe North', max_length=100)),
                ('education_level', models.CharField(choices=[('Bachelor Degree', 'Bachelor Degree'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Masters', 'Masters'), ('PHD', 'PHD')], default='Bachelor Degree', max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
